# Project information
site_name: YouTube Live Lecture
# define TOC or order of website-
nav:
  - Home: index.md
  - Lecture 06: lec06.md
  - Lecture 05: lec05.md
  - Lecture 04: lec04.md
  - Lecture 03: lec03.md
  - Lecture 02: lec02.md
  - Lecture 01: lec01.md


site_author: Sunny Bhaveen Chandra
site_description: >-
  DESCRIPTION

# Repository
repo_name: c17hawke/YouTube-Live-Classes
repo_url: https://github.com/c17hawke/YouTube-Live-Classes

# extra_css:
#   - stylesheets/extra.css

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime  

  
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/c17hawke
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/c17hawke
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/c17hawke
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/c17hawke/

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.arithmatex
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.highlight

  
  
plugins:
  - search

copyright: |
  &copy; 2022 <a href="https://github.com/c17hawke"  target="_blank" rel="noopener">Sunny Bhaveen Chandra</a>